#!/usr/bin/env python3
"""
Regenereert functions/_data.js vanuit de brondata in data/.

Gebruik (vanuit de projectroot be-tv-cf/):
    python3 scripts/build_data.py

Verwacht de volgende bronbestanden in data/:
    - channels.json   { "categories": {...}, "channels": [...] }
    - epg_cache.json  { "generated_at": "...", "programmes": {...} }
    - stream_map.json { "<iptv_id>": ["<stream_url>", ...], ... }

Als je de originele Flask-app (be-tv-app/) nog hebt, kan je channels.json
opnieuw exporteren met:

    python3 -c "
    import json
    from importlib.util import spec_from_file_location, module_from_spec
    spec = spec_from_file_location('channels', 'be-tv-app/data/channels.py')
    m = module_from_spec(spec); spec.loader.exec_module(m)
    json.dump({'categories': m.CATEGORIES, 'channels': m.CHANNELS},
               open('be-tv-cf/data/channels.json', 'w'), ensure_ascii=False, indent=2)
    "
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA_DIR = os.path.join(ROOT, "data")
OUT_PATH = os.path.join(ROOT, "functions", "_data.js")


def main():
    channels_data = json.load(open(os.path.join(DATA_DIR, "channels.json"), encoding="utf-8"))
    epg = json.load(open(os.path.join(DATA_DIR, "epg_cache.json"), encoding="utf-8"))
    try:
        stream_map = json.load(open(os.path.join(DATA_DIR, "stream_map.json"), encoding="utf-8"))
    except FileNotFoundError:
        stream_map = {}

    lines = [
        "// Auto-generated by scripts/build_data.py — do not hand-edit.",
        "// Regenerate with: python3 scripts/build_data.py",
        "export const CATEGORIES = " + json.dumps(channels_data["categories"], ensure_ascii=False) + ";",
        "export const CHANNELS = " + json.dumps(channels_data["channels"], ensure_ascii=False) + ";",
        "export const EPG_GENERATED_AT = " + json.dumps(epg.get("generated_at")) + ";",
        "export const PROGRAMMES = " + json.dumps(epg.get("programmes", {}), ensure_ascii=False) + ";",
        "export const STREAM_MAP = " + json.dumps(stream_map, ensure_ascii=False) + ";",
    ]

    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {OUT_PATH} ({os.path.getsize(OUT_PATH)} bytes)")
    print(f"  channels: {len(channels_data['channels'])}")
    print(f"  categories: {len(channels_data['categories'])}")
    print(f"  epg generated_at: {epg.get('generated_at')}")
    print(f"  stream_map entries: {len(stream_map)}")


if __name__ == "__main__":
    main()
